service: ${file(config.${self:provider.stage}.json):serviceName}

# Where the service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2
  profile: ${file(config.${self:provider.stage}.json):awsProfile}
  memorySize: 512
  timeout: 5

package:
  include:
    - addEmail.js
    - confirmEmail.js
    - deleteEmail.js
  exclude:
    - .git/**
    - .gitignore
    - README.md
    - LICENSE
    - config.*.json
    - addEmail.coffee
    - confirmEmail.coffee
    - deleteEmail.coffee

# Export some cloud formation information
resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}
  Outputs:
    S3BucketName:
      Description: The ARN for the S3 bucket
      Value:
        "Fn::GetAtt": [ S3Bucket, Arn ]
      Export:
        Name: ${self:service}:${self:provider.stage}:S3BucketName


# Deployable functions
functions:
  addEmail:
    handler: addEmail.handler
    description: Request to add a users email
    events:
      - http:
          path: accounts
          method: put
          cors: true
  confirmEmail:
    handler: confirmEmail.handler
    description: Confirm the email address is valid
    events:
      - http:
          path: accounts/confirm
          method: post
          cors: true
  deleteEmail:
    handler: deleteEmail.handler
    description: Delete the email address
    events:
      - http:
          path: accounts
          method: delete
          cors: true
