service: ${self:custom.serviceName}

custom: ${file(config.${self:provider.stage}.json)}

# Where the service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2
  profile: ${self:custom.awsProfile}
  memorySize: 512
  timeout: 5
  environment:
    stage: ${self:provider.stage}
    serviceEndpoint: ${self:custom.serviceEndpoint}
    bucketName: ${self:custom.bucketName}
    awsSesArn: ${self:custom.awsSesArn}
    awsSesRegion: ${self:custom.awsSesRegion}
    sourceEmail: ${self:custom.sourceEmail}
    replyToEmail: ${self:custom.replyToEmail}
    confirmEmailTemplateSubject: ${self:custom.confirmEmailTemplate.subject}
    confirmEmailTemplateBodyText: ${self:custom.confirmEmailTemplate.bodyText}
    confirmEmailTemplateBodyHtml: ${self:custom.confirmEmailTemplate.bodyHtml}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
        - "s3:DeleteObject"
        - "s3:ListBucket" #ListBucket enabled 404 responses for failed GetObject calls
      Resource:
        - arn:aws:s3:::${self:custom.bucketName}
        - arn:aws:s3:::${self:custom.bucketName}/*
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource:
        - ${self:custom.awsSesArn}

package:
  include:
    - handler.js
  exclude:
    - .git/**
    - .gitignore
    - README.md
    - LICENSE
    - config.*.json
    - handler.coffee

# Export some cloud formation information
resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
  Outputs:
    S3BucketName:
      Description: The ARN for the S3 bucket
      Value:
        "Fn::GetAtt": [ S3Bucket, Arn ]
      Export:
        Name: ${self:service}:${self:provider.stage}:S3BucketName


# Deployable functions
functions:
  addEmail:
    handler: handler.addEmail
    description: Request to add a users email
    events:
      - http:
          path: accounts
          method: put
          cors: true
  confirmEmail:
    handler: handler.confirmEmail
    description: Confirm the email address is valid
    events:
      - http:
          path: accounts/confirm
          method: get
          cors: true
          request:
            template:
              application/json: '{"email": "$input.params(''email'')", "token": "$input.params(''token'')"}'
  deleteEmail:
    handler: handler.deleteEmail
    description: Delete the email address
    events:
      - http:
          path: accounts
          method: delete
          cors: true
