service: email-account-management

# Where the service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-2
  profile: catfacts #TODO Replace this with your AWS profile
  memorySize: 512
  timeout: 5

package:
  exclude:
    .git/**

plugins:
  # Mmm coffeescript
  - serverless-coffeescript

# Export some cloud formation information
resources:
  Resource:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}
  Outputs:
    S3BucketName:
      Description: The ARN for the S3 bucket
      Value:
        "Fn::GetAtt": [ S3Bucket, Arn ]
      Export:
        Name: ${self:service}:${opt:stage}:S3BucketName


# Deployable functions
functions:
  addEmail:
    handler: handler.addEmail
    description: Request to add a users email
    events:
      - http:
          path: account
          method: put
          cors: true
  confirmEmail:
    handler: handler.confirmEmail
    description: Confirm the email address is valid
    events:
      - http:
          path: account
          method: post
          cors: true
  deleteEmail:
    handler: handler.deleteEmail
    description: Delete the email address
    events:
      - http:
          path: account
          method: delete
          cors: true
